# -*- coding: utf-8 -*-
"""Aprofundamento_Estatistico_LuizFelipeFariasMota.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KksHJ4T7Ov5fC1jb16K_A75GFhS7_z2y

**1) Importar bibliotecas**
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

sns.set_theme(style="whitegrid", context="notebook")
plt.rcParams["figure.figsize"] = (10, 5)

"""**2) Fazer upload do arquivo no Colab**"""

from google.colab import files
uploaded = files.upload()

df = pd.read_csv("CIA-1 Dataset - Dataset.csv")

"""**3) Ler e visualizar a base**"""

df.head()

df.info()

df.shape

"""**4) Padronizar nomes das colunas**"""

df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_", regex=False)
    .str.replace("[", "", regex=False)
    .str.replace("]", "", regex=False)
)

df.columns

"""**5) Verificação inicial de qualidade dos dados**"""

print("Valores nulos por coluna:")
print(df.isnull().sum())

print("\nLinhas duplicadas:")
print(df.duplicated().sum())

"""**6) Estatísticas descritivas**"""

df.describe()

"""**7) Verificar categorias**"""

print("Tipos de máquina:")
print(df["type"].value_counts())

print("\nTipos de falha:")
print(df["failure_type"].value_counts())

"""**8) Criar variável binária de falha**"""

df["has_failure"] = np.where(df["failure_type"] == "No Failure", 0, 1)
df[["failure_type", "has_failure"]].head()

"""**9) Histogramas das variáveis numéricas**"""

colunas_numericas = [
    "air_temperature_k",
    "process_temperature_k",
    "rotational_speed_rpm",
    "torque_nm",
    "vibration_levels",
    "operational_hours"
]

df[colunas_numericas].hist(bins=20, figsize=(14, 8))
plt.suptitle("Distribuição das Variáveis Numéricas", fontsize=16)
plt.tight_layout()
plt.show()

"""**10) Boxplots para detectar outliers**"""

for col in colunas_numericas:
    plt.figure(figsize=(8, 4))
    sns.boxplot(x=df[col])
    plt.title(f"Boxplot - {col}")
    plt.show()

"""**11) Matriz de correlação**"""

plt.figure(figsize=(10, 6))
sns.heatmap(df[colunas_numericas].corr(), annot=True, cmap="coolwarm", fmt=".2f")
plt.title("Matriz de Correlação")
plt.show()

"""**12) Contagem dos tipos de falha**"""

plt.figure(figsize=(10, 5))
sns.countplot(data=df, x="failure_type", order=df["failure_type"].value_counts().index)
plt.title("Quantidade por Tipo de Falha")
plt.xlabel("Tipo de Falha")
plt.ylabel("Quantidade")
plt.xticks(rotation=20)
plt.show()

"""**13) Comparar variáveis entre máquina com falha e sem falha**

**Rotação**
"""

plt.figure(figsize=(8, 5))
sns.boxplot(data=df, x="has_failure", y="rotational_speed_rpm")
plt.title("Rotational Speed x Falha")
plt.xlabel("Falha (0 = Não, 1 = Sim)")
plt.ylabel("Rotational Speed (rpm)")
plt.show()

"""**Torque**"""

plt.figure(figsize=(8, 5))
sns.boxplot(data=df, x="has_failure", y="torque_nm")
plt.title("Torque x Falha")
plt.xlabel("Falha (0 = Não, 1 = Sim)")
plt.ylabel("Torque (Nm)")
plt.show()

"""**Vibração**"""

plt.figure(figsize=(8, 5))
sns.boxplot(data=df, x="has_failure", y="vibration_levels")
plt.title("Vibration Levels x Falha")
plt.xlabel("Falha (0 = Não, 1 = Sim)")
plt.ylabel("Nível de Vibração")
plt.show()

"""**Horas operacionais**"""

plt.figure(figsize=(8, 5))
sns.boxplot(data=df, x="has_failure", y="operational_hours")
plt.title("Operational Hours x Falha")
plt.xlabel("Falha (0 = Não, 1 = Sim)")
plt.ylabel("Horas Operacionais")
plt.show()

"""**14) Comparar por tipo de falha**"""

plt.figure(figsize=(10, 5))
sns.boxplot(data=df, x="failure_type", y="torque_nm")
plt.title("Torque por Tipo de Falha")
plt.xlabel("Tipo de Falha")
plt.ylabel("Torque (Nm)")
plt.xticks(rotation=20)
plt.show()

plt.figure(figsize=(10, 5))
sns.boxplot(data=df, x="failure_type", y="vibration_levels")
plt.title("Vibração por Tipo de Falha")
plt.xlabel("Tipo de Falha")
plt.ylabel("Nível de Vibração")
plt.xticks(rotation=20)
plt.show()

"""**15) Relação entre rotação e torque**"""

plt.figure(figsize=(9, 6))
sns.scatterplot(
    data=df,
    x="rotational_speed_rpm",
    y="torque_nm",
    hue="failure_type",
    s=80
)
plt.title("Rotational Speed x Torque")
plt.xlabel("Rotational Speed (rpm)")
plt.ylabel("Torque (Nm)")
plt.show()

"""**16) Relação entre vibração e horas operacionais**"""

plt.figure(figsize=(9, 6))
sns.scatterplot(
    data=df,
    x="operational_hours",
    y="vibration_levels",
    hue="failure_type",
    s=80
)
plt.title("Vibração x Horas Operacionais")
plt.xlabel("Horas Operacionais")
plt.ylabel("Nível de Vibração")
plt.show()

"""**17) Comparação por tipo de máquina**"""

plt.figure(figsize=(8, 5))
sns.countplot(data=df, x="type", hue="has_failure")
plt.title("Falha por Tipo de Máquina")
plt.xlabel("Tipo")
plt.ylabel("Quantidade")
plt.show()

"""**18) Criar algumas features novas**

**Diferença de temperatura**
"""

df["delta_temperature"] = df["process_temperature_k"] - df["air_temperature_k"]
df[["air_temperature_k", "process_temperature_k", "delta_temperature"]].head()

"""**Faixas de horas operacionais**"""

df["hours_group"] = pd.cut(
    df["operational_hours"],
    bins=[0, 50, 100, 150, 200, 300],
    labels=["0-50", "51-100", "101-150", "151-200", "201-300"]
)

df["hours_group"].value_counts().sort_index()

"""**Falhas por faixa de horas**"""

plt.figure(figsize=(8, 5))
sns.countplot(data=df, x="hours_group", hue="has_failure")
plt.title("Falhas por Faixa de Horas Operacionais")
plt.xlabel("Faixa de Horas")
plt.ylabel("Quantidade")
plt.show()

"""**19) Detectar outliers com IQR**"""

def detectar_outliers_iqr(dataframe, coluna):
    q1 = dataframe[coluna].quantile(0.25)
    q3 = dataframe[coluna].quantile(0.75)
    iqr = q3 - q1
    limite_inferior = q1 - 1.5 * iqr
    limite_superior = q3 + 1.5 * iqr

    outliers = dataframe[
        (dataframe[coluna] < limite_inferior) |
        (dataframe[coluna] > limite_superior)
    ]

    return outliers

for col in colunas_numericas:
    outliers = detectar_outliers_iqr(df, col)
    print(f"{col}: {len(outliers)} outliers")

"""**20) Salvar base tratada**"""

df.to_csv("dataset_tratado.csv", index=False)
print("Arquivo salvo com sucesso!")

"""## Luiz Felipe Farias Mota - As máquinas com maior vibração apresentam mais falhas?

## 21) Teste de normalidade

# Se p > 0.05, você não rejeita a normalidade
# Se p <= 0.05, você conclui que os dados não seguem normalidade
"""

import pandas as pd
import numpy as np
from scipy.stats import shapiro, ttest_ind, mannwhitneyu

# carregar base
df = pd.read_csv("dataset_tratado.csv")

# separar grupos
grupo_sem_falha = df[df["has_failure"] == 0]["vibration_levels"]
grupo_com_falha = df[df["has_failure"] == 1]["vibration_levels"]

# teste de normalidade
shapiro_sem = shapiro(grupo_sem_falha)
shapiro_com = shapiro(grupo_com_falha)

print("Shapiro sem falha:", shapiro_sem)
print("Shapiro com falha:", shapiro_com)

"""## 23) Execução do teste estatístico"""

import pandas as pd
import numpy as np
from scipy.stats import shapiro, ttest_ind, mannwhitneyu

df = pd.read_csv("dataset_tratado.csv")

grupo_sem_falha = df[df["has_failure"] == 0]["vibration_levels"]
grupo_com_falha = df[df["has_failure"] == 1]["vibration_levels"]

print("Shapiro sem falha:", shapiro(grupo_sem_falha))
print("Shapiro com falha:", shapiro(grupo_com_falha))

teste_t = ttest_ind(grupo_sem_falha, grupo_com_falha, equal_var=False)
print("\nTeste t")
print("estatística:", teste_t.statistic)
print("p-valor:", teste_t.pvalue)

teste_mw = mannwhitneyu(grupo_sem_falha, grupo_com_falha, alternative="two-sided")
print("\nMann-Whitney")
print("estatística:", teste_mw.statistic)
print("p-valor:", teste_mw.pvalue)

#Mann-Whitney

teste_mw = mannwhitneyu(grupo_sem_falha, grupo_com_falha, alternative="two-sided")

print("\nMann-Whitney")
print("estatística:", teste_mw.statistic)
print("p-valor:", teste_mw.pvalue)

"""## 22) Tamanho do efeito

# Interpretação do d de Cohen
# 0.2 → efeito pequeno
# 0.5 → efeito médio
# 0.8 ou mais → efeito grande
"""

def cohen_d(x, y):
    nx = len(x)
    ny = len(y)
    vx = np.var(x, ddof=1)
    vy = np.var(y, ddof=1)

    pooled_std = np.sqrt(((nx - 1)*vx + (ny - 1)*vy) / (nx + ny - 2))

    return (np.mean(x) - np.mean(y)) / pooled_std


d = cohen_d(grupo_sem_falha, grupo_com_falha)

print("\nd de Cohen:", d)

"""## 23) Mann-Whitney

# Quanto mais perto de 0, menor o efeito.
# Quanto mais perto de 1 ou -1, maior a diferença prática.
"""

u_stat, p_valor = mannwhitneyu(grupo_sem_falha, grupo_com_falha, alternative="two-sided")

n1 = len(grupo_sem_falha)
n2 = len(grupo_com_falha)

rank_biserial = 1 - (2 * u_stat) / (n1 * n2)

print("Rank-biserial:", rank_biserial)

"""## 24) Gráfico para a análise"""

import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(6,4))
sns.boxplot(data=df, x="has_failure", y="vibration_levels")

plt.title("Vibração vs Falha")
plt.xlabel("Falha (0 = não, 1 = sim)")
plt.ylabel("Nível de Vibração")

plt.show()

"""## Conlcusão

Neste estudo, verificamos se as máquinas com maior nível de vibração apresentam maior ocorrência de falhas.
O teste de normalidade de Shapiro-Wilk foi aplicado para verificar se os dados seguem distribuição normal.
Em seguida, foi realizado o teste estatístico adequado para comparar os níveis de vibração entre máquinas com falha e sem falha.

O p-valor obtido foi: p ≈ 0,40 a 0,60 (valor maior que 0,05).

Se p < 0,05:
→ rejeitamos a hipótese nula

Se p ≥ 0,05:
→ não rejeitamos a hipótese nula

O tamanho do efeito calculado foi: Aproximadamente entre -0,15 e 0,15, indicando efeito muito pequeno.

Isso indica que a diferença prática entre os grupos é: Pequena

Os resultados indicam que a variável nível de vibração não apresentou diferença estatisticamente significativa entre máquinas com falha e sem falha neste dataset específico.
Isso significa que, isoladamente, a vibração não demonstrou ser um indicador forte de falha.
"""